"""Add government_id column to user table

Revision ID: 08db7163ae71
Revises: 42c5c9ca9d48
Create Date: 2025-03-31 00:22:06.719777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08db7163ae71'
down_revision = '42c5c9ca9d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('government_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('government_id')

    # ### end Alembic commands ###
