"""Add mime_type to Document model

Revision ID: d18f78edd660
Revises: e3e239d6f09d
Create Date: 2025-03-31 02:09:16.918295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18f78edd660'
down_revision = 'e3e239d6f09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('mime_type')

    # ### end Alembic commands ###
