"""Add phone and email columns to application table

Revision ID: e3e239d6f09d
Revises: 08db7163ae71
Create Date: 2025-03-31 01:37:05.236492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e239d6f09d'
down_revision = '08db7163ae71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('father_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('aadhaar_number', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_relation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_phone', sa.String(length=15), nullable=True))
        batch_op.alter_column('application_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('dob',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('application_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('next_of_kin_phone')
        batch_op.drop_column('next_of_kin_relation')
        batch_op.drop_column('next_of_kin')
        batch_op.drop_column('aadhaar_number')
        batch_op.drop_column('father_name')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
